import { Component } from '@angular/core';
import {Subject} from "./subject";
import {NgForm} from "@angular/forms";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'lab_5';
  select = '';
  counter = 0;
  sum = 0;
  is_show_universities = false;
  done_subjects: Subject[] = [];

  universities = [
    {
      name: "Самарский государственный технический университет",
      shortName: "СамГТУ",
      departments: [
        {
          codeSpeciality: "01.03.02",
          nameSpeciality: "Прикладная математика и информатика",
          subjects: ["Русский язык", "Математика"],
          // multipleSubjects: [["ИКТ", "Физика"], ["Обществознание", "История"], ["Биология", "Химия"]],
          // multipleSubjects: [["ИКТ", "Физика"], ["Обществознание", "История"]],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 216,
        },
        {
          codeSpeciality: "04.03.01",
          nameSpeciality: "Химия",
          subjects: ["Русский язык", "Химия"],
          multipleSubjects: [["Биология", "Математика"]],
          additionalSubject: false,
          averageScore: 165,
        },
        {
          codeSpeciality: "04.03.02",
          nameSpeciality: "Химия, физика и механика материалов",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["Физика", "Химия"]],
          additionalSubject: false,
          averageScore: 127,
        },

        {
          codeSpeciality: "07.03.01",
          nameSpeciality: "Архитектура",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [],
          additionalSubject: true,
          averageScore: 126,
        },
        {
          codeSpeciality: "07.03.02",
          nameSpeciality: "Реконструкция и реставрация архитектурного наследия",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [],
          additionalSubject: true,
          averageScore: 149,
        },
        {
          codeSpeciality: "07.03.03",
          nameSpeciality: "Дизайн архитектурной среды",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [],
          additionalSubject: true,
          averageScore: 174,
        },
        {
          codeSpeciality: "07.03.04",
          nameSpeciality: "Градостроительство",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [],
          additionalSubject: true,
          averageScore: 161,
        },
        {
          codeSpeciality: "08.03.01",
          nameSpeciality: "Строительство",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 142,
        },
        {
          codeSpeciality: "09.03.01",
          nameSpeciality: "Информатика и вычислительная техника",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 195,
        },
        {
          codeSpeciality: "09.03.02",
          nameSpeciality: "Информационные системы и технологии",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 216,
        },
        {
          codeSpeciality: "09.03.03",
          nameSpeciality: "Прикладная информатика",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 188,
        },
        {
          codeSpeciality: "09.03.04",
          nameSpeciality: "Программная инженерия",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 220,
        },
        {
          codeSpeciality: "10.03.01",
          nameSpeciality: "Информационная безопасность",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 167,
        },
        {
          codeSpeciality: "11.03.01",
          nameSpeciality: "Радиотехника",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 157,
        },
        {
          codeSpeciality: "12.03.01",
          nameSpeciality: "Приборостроение",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 181,
        },
        {
          codeSpeciality: "13.03.01",
          nameSpeciality: "Теплоэнергетика и теплотехника",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 134,
        },
        {
          codeSpeciality: "13.03.02",
          nameSpeciality: "Электроэнергетика и электротехника",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 144,
        },
        {
          codeSpeciality: "15.03.01",
          nameSpeciality: "Машиностроение",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 145,
        },
        {
          codeSpeciality: "15.03.02",
          nameSpeciality: "Технологические машины и оборудование",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 144,
        },
        {
          codeSpeciality: "15.03.04",
          nameSpeciality: "Автоматизация технологических процессов и производств",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 165,
        },
        {
          codeSpeciality: "15.03.05",
          nameSpeciality:
            "Конструкторско-технологическое обеспечение машиностроительных производств",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 142,
        },
        {
          codeSpeciality: "18.03.01",
          nameSpeciality: "Химическая технология",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["Физика", "Химия"]],
          additionalSubject: false,
          averageScore: 138,
        },
        {
          codeSpeciality: "18.03.02",
          nameSpeciality:
            "Энерго- и ресурсосберегающие процессы химической технологии, нефтехимии биотехнологии",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["Физика", "Химия"]],
          additionalSubject: false,
          averageScore: 144,
        },
        {
          codeSpeciality: "19.03.01",
          nameSpeciality: "Биотехнология",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["Биология", "Химия"]],
          additionalSubject: false,
          averageScore: 192,
        },
        {
          codeSpeciality: "19.03.02",
          nameSpeciality: "Продукты питания из растительного сырья",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["Физика", "Химия"]],
          additionalSubject: false,
          averageScore: 137,
        },
        {
          codeSpeciality: "19.03.04",
          nameSpeciality:
            "Технология продукции и организация общественного питания",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["Биология", "Химия"]],
          additionalSubject: false,
          averageScore: 175,
        },
        {
          codeSpeciality: "20.03.01",
          nameSpeciality: "Техносферная безопасность",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 134,
        },
        {
          codeSpeciality: "21.03.01",
          nameSpeciality: "Нефтегазовое дело",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 147,
        },
        {
          codeSpeciality: "22.03.01",
          nameSpeciality: "Материаловедение и технологии материалов",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 131,
        },
        {
          codeSpeciality: "22.03.02",
          nameSpeciality: "Металлургия",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 144,
        },
        {
          codeSpeciality: "23.03.01",
          nameSpeciality: "Технология транспортных процессов",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 179,
        },
        {
          codeSpeciality: "23.03.03",
          nameSpeciality:
            "Эксплуатация транспортно-технологических машин и комплексов",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 169,
        },
        {
          codeSpeciality: "27.03.01",
          nameSpeciality: "Стандартизация и метрология",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 151,
        },
        {
          codeSpeciality: "27.03.02",
          nameSpeciality: "Управление качеством",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 184,
        },
        {
          codeSpeciality: "27.03.03",
          nameSpeciality: "Системный анализ и управление",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 180,
        },
        {
          codeSpeciality: "27.03.04",
          nameSpeciality: "Управление в технических системах",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 145,
        },
        {
          codeSpeciality: "29.03.04",
          nameSpeciality: "Технология художественной обработки материалов",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 146,
        },
        {
          codeSpeciality: "29.03.05",
          nameSpeciality: "Конструирование изделий легкой промышленности",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [],
          additionalSubject: true,
          averageScore: 123,
        },
        {
          codeSpeciality: "35.03.10",
          nameSpeciality: "Ландшафтная архитектура",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["Биология", "Физика"]],
          additionalSubject: false,
          averageScore: 141,
        },
        {
          codeSpeciality: "38.03.02",
          nameSpeciality: "Менеджмент",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["История", "Обществознание"]],
          additionalSubject: false,
          averageScore: 242,
        },
        {
          codeSpeciality: "54.03.01",
          nameSpeciality: "Дизайн",
          subjects: ["Русский язык", "Литература"],
          multipleSubjects: [],
          additionalSubject: true,
          averageScore: 142,
        },
        {
          codeSpeciality: "04.05.01",
          nameSpeciality: "Фундаментальная и прикладная химия",
          subjects: ["Физика", "Математика", "Химия"],
          multipleSubjects: [],
          additionalSubject: false,
          averageScore: 206,
        },
        {
          codeSpeciality: "08.05.01",
          nameSpeciality: "Строительство уникальных зданий и сооружений",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 139,
        },
        {
          codeSpeciality: "17.05.01",
          nameSpeciality: "Боеприпасы и взрыватели",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 154,
        },
        {
          codeSpeciality: "18.05.01",
          nameSpeciality:
            "Химическая технология энергонасыщенных материалов и изделий",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["Физика", "Химия"]],
          additionalSubject: false,
          averageScore: 135,
        },
        {
          codeSpeciality: "21.05.02",
          nameSpeciality: "Прикладная геология",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 178,
        },
        {
          codeSpeciality: "21.05.05",
          nameSpeciality:
            "Физические процессы горного или нефтегазового производства",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 191,
        },
      ],
    },
    {
      name: "Самарский национальный исследовательский университет имени академика С. П. Королёва",
      shortName: "Самарский университет (СНИУ)",
      departments: [
        {
          codeSpeciality: "01.03.02",
          nameSpeciality: "Прикладная математика и информатика",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 227,
        },
        {
          codeSpeciality: "01.03.03",
          nameSpeciality:
            "Механика и математическое моделирование (Анализ и компьютерное моделирование аэрокосмических систем)",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 194,
        },
        {
          codeSpeciality: "01.03.03",
          nameSpeciality:
            "Механика и математическое моделирование (Вычислительная механика)",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 154,
        },
        {
          codeSpeciality: "01.05.01",
          nameSpeciality: "Фундаментальные математика и механика",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 140,
        },
        {
          codeSpeciality: "02.03.01",
          nameSpeciality: "Математика и компьютерные науки",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 190,
        },
        {
          codeSpeciality: "02.03.02",
          nameSpeciality:
            "Фундаментальные информатика и информационные технологии",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 238,
        },
        {
          codeSpeciality: "02.03.03",
          nameSpeciality:
            "Математическое обеспечение и администрирование информационных систем",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 188,
        },
        {
          codeSpeciality: "03.03.01",
          nameSpeciality: "Прикладные математика и физика",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 194,
        },
        {
          codeSpeciality: "03.03.02",
          nameSpeciality: "Физика",
          subjects: ["Русский язык", "Физика"],
          multipleSubjects: [["ИКТ", "Математика"]],
          additionalSubject: false,
          averageScore: 152,
        },
        {
          codeSpeciality: "04.03.01",
          nameSpeciality: "Химия",
          subjects: ["Русский язык", "Химия"],
          multipleSubjects: [["Биология", "Математика"]],
          additionalSubject: false,
          averageScore: 189,
        },
        {
          codeSpeciality: "04.05.01",
          nameSpeciality: "Фундаментальная и прикладная химия",
          subjects: ["Русский язык", "Химия"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 223,
        },
        {
          codeSpeciality: "06.03.01",
          nameSpeciality: "Биология",
          subjects: ["Русский язык", "Математика", "Биология"],
          multipleSubjects: [],
          additionalSubject: false,
          averageScore: 181,
        },
        {
          codeSpeciality: "09.03.01",
          nameSpeciality: "Информатика и вычислительная техника",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 219,
        },
        {
          codeSpeciality: "10.03.01",
          nameSpeciality: "Информационная безопасность",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 194,
        },
        {
          codeSpeciality: "10.05.01",
          nameSpeciality: "Компьютерная безопасность",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 184,
        },
        {
          codeSpeciality: "10.05.03",
          nameSpeciality: "Информационная безопасность автоматизированных систем",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 226,
        },
        {
          codeSpeciality: "11.03.03",
          nameSpeciality: "Конструирование и технология электронных средств",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 168,
        },
        {
          codeSpeciality: "11.03.04",
          nameSpeciality: "Электроника и наноэлектроника",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 176,
        },
        {
          codeSpeciality: "11.05.01",
          nameSpeciality: "Радиоэлектронные системы и комплексы",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 151,
        },

        {
          codeSpeciality: "12.03.03",
          nameSpeciality: "Фотоника и оптоинформатика",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 196,
        },
        {
          codeSpeciality: "12.03.04",
          nameSpeciality: "Биотехнические системы и технологии",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["Биология", "Физика"]],
          additionalSubject: false,
          averageScore: 202,
        },
        {
          codeSpeciality: "12.03.05",
          nameSpeciality: "Лазерная техника и лазерные технологии",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 192,
        },
        {
          codeSpeciality: "13.03.03",
          nameSpeciality: "Энергетическое машиностроение",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 136,
        },
        {
          codeSpeciality: "15.03.01",
          nameSpeciality: "Машиностроение",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 180,
        },
        {
          codeSpeciality: "15.03.04",
          nameSpeciality: "Автоматизация технологических процессов и производств",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 186,
        },
        {
          codeSpeciality: "15.03.05",
          nameSpeciality:
            "Конструкторско-технологическое обеспечение машиностроительных производств",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 149,
        },
        {
          codeSpeciality: "22.03.02",
          nameSpeciality: "Металлургия",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["Физика", "Химия"]],
          additionalSubject: false,
          averageScore: 144,
        },
        {
          codeSpeciality: "23.03.01",
          nameSpeciality: "Технология транспортных процессов",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 177,
        },
        {
          codeSpeciality: "24.03.01",
          nameSpeciality: "Ракетные комплексы и космонавтика",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 139,
        },
        {
          codeSpeciality: "24.03.04",
          nameSpeciality: "Авиастроение",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 191,
        },
        {
          codeSpeciality: "24.03.05",
          nameSpeciality: "Двигатели летательных аппаратов",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 141,
        },
        {
          codeSpeciality: "24.05.01",
          nameSpeciality:
            "Проектирование, производство и эксплуатация ракет и ракетнокосмических комплексов",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 161,
        },
        {
          codeSpeciality: "24.05.02",
          nameSpeciality: "Проектирование авиационных и ракетных двигателей",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 175,
        },
        {
          codeSpeciality: "24.05.07",
          nameSpeciality: "Самолето- и вертолетостроение",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 129,
        },
        {
          codeSpeciality: "25.03.01",
          nameSpeciality:
            "Техническая эксплуатация летательных аппаратов и двигателей",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 164,
        },
        {
          codeSpeciality: "25.03.02",
          nameSpeciality:
            "Техническая эксплуатация авиационных электросистем и пилотажнонавигационных комплексов",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 157,
        },
        {
          codeSpeciality: "27.03.02",
          nameSpeciality: "Управление качеством",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 150,
        },
        {
          codeSpeciality: "28.03.02",
          nameSpeciality: "Наноинженерия",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["ИКТ", "Физика"]],
          additionalSubject: false,
          averageScore: 140,
        },
        {
          codeSpeciality: "37.03.01",
          nameSpeciality: "Психология",
          subjects: ["Русский язык", "Математика"],
          multipleSubjects: [["Физика", "Химия"]],
          additionalSubject: false,
          averageScore: 247,
        },
        {
          codeSpeciality: "39.03.01",
          nameSpeciality: "Социология",
          subjects: ["Русский язык", "Обществознание"],
          multipleSubjects: [["ИКТ", "Математика"]],
          additionalSubject: false,
          averageScore: 240,
        },
        {
          codeSpeciality: "39.03.02",
          nameSpeciality: "Социальная работа",
          subjects: ["Русский язык", "Обществознание", "История"],
          multipleSubjects: [],
          additionalSubject: false,
          averageScore: 197,
        },
        {
          codeSpeciality: "40.03.01",
          nameSpeciality: "Юриспруденция",
          subjects: ["Русский язык", "Обществознание"],
          multipleSubjects: [["ИКТ", "История"]],
          additionalSubject: false,
          averageScore: 279,
        },
        {
          codeSpeciality: "41.03.05",
          nameSpeciality: "Международные отношения",
          subjects: ["Русский язык", "Иностранный язык", "История"],
          multipleSubjects: [],
          additionalSubject: false,
          averageScore: 266,
        },
        {
          codeSpeciality: "42.03.01",
          nameSpeciality: "Реклама и связи с общественностью",
          subjects: ["Русский язык", "Обществознание", "История"],
          multipleSubjects: [],
          additionalSubject: false,
          averageScore: 263,
        },
        {
          codeSpeciality: "42.03.02",
          nameSpeciality: "Журналистика",
          subjects: ["Русский язык", "Обществознание"],
          multipleSubjects: [],
          additionalSubject: true,
          averageScore: 277,
        },
        {
          codeSpeciality: "42.03.04",
          nameSpeciality: "Телевидение",
          subjects: ["Русский язык", "Литература"],
          multipleSubjects: [],
          additionalSubject: true,
          averageScore: 279,
        },
        {
          codeSpeciality: "44.03.01",
          nameSpeciality: "Педагогическое образование",
          subjects: ["Русский язык", "Обществознание", "Литература"],
          multipleSubjects: [],
          additionalSubject: false,
          averageScore: 215,
        },
        {
          codeSpeciality: "44.03.02",
          nameSpeciality: "Психолого-педагогическое образование",
          subjects: ["Русский язык", "Биология"],
          multipleSubjects: [["Математика", "Обществознание"]],
          additionalSubject: false,
          averageScore: 231,
        },
        {
          codeSpeciality: "44.03.05",
          nameSpeciality:
            "Педагогическое образование (с двумя профилями подготовки)",
          subjects: ["Русский язык", "Обществознание", "Иностранный язык"],
          multipleSubjects: [],
          additionalSubject: false,
          averageScore: 278,
        },
        {
          codeSpeciality: "45.03.01",
          nameSpeciality: "Филология (Зарубежная филология)",
          subjects: ["Русский язык", "Иностранный язык", "Литература"],
          multipleSubjects: [],
          additionalSubject: false,
          averageScore: 271,
        },
        {
          codeSpeciality: "45.03.01",
          nameSpeciality: "Филология (Отечественная филология)",
          subjects: ["Русский язык", "Литература"],
          multipleSubjects: [["История", "Обществознание"]],
          additionalSubject: false,
          averageScore: 253,
        },
        {
          codeSpeciality: "45.03.02",
          nameSpeciality: "Лингвистика",
          subjects: ["Русский язык", "Иностранный язык"],
          multipleSubjects: [["История", "Литература"]],
          additionalSubject: false,
          averageScore: 283,
        },
        {
          codeSpeciality: "46.03.01",
          nameSpeciality: "История",
          subjects: ["Русский язык", "История"],
          multipleSubjects: [["Литература", "Обществознание"]],
          additionalSubject: false,
          averageScore: 243,
        },
        {
          codeSpeciality: "46.03.02",
          nameSpeciality:
            "Документоведение и архивоведение (заочная форма обучения)",
          subjects: ["Русский язык", "История"],
          multipleSubjects: [["Литература", "Обществознание"]],
          additionalSubject: false,
          averageScore: 196,
        },
      ],
    },
  ];

  add_subject(f: NgForm){
    let json = f.value;
    this.select = json.sel_obj;
    this.counter = json.points;
    let new_sub = new Subject(this.select, this.counter);
    this.done_subjects.push(new_sub);
  }
  del_subject(){
    this.done_subjects.pop();
  }
  show_list(){
    let name_subj = [];
    for(let i = 0; i < this.done_subjects.length; i++){
      this.sum += this.done_subjects[i].count
      name_subj.push(this.done_subjects[i].name);
    }
    console.log(this.sum);
    console.log(name_subj);
    if(!this.is_show_universities) this.is_show_universities = true;
    else this.is_show_universities = false;
  }
}
